import {api,body} from './api.js';import {state} from './state.js';import {openWindow,closeActive,focus} from '../shell/windowManager.js';import {fileCommand} from '../apps/apps.js';import type {AppDefinition,Settings} from '../../shared/types/domain.js';
const os=document.querySelector('#os')!;let clock:number,noteTimer:number|undefined;
async function boot(){const apps=await api<AppDefinition[]>('/apps');state.apps=apps;state.settings=await api<Settings>('/settings');applySettings(state.settings);os.innerHTML=`<div class="workspace"><nav class="topbar"><button class="brand">fluida</button><button data-command>⌕ Search</button><span data-clock></span><button data-quick>Quick settings</button><button data-notifications>●</button></nav><div class="shortcuts">${state.apps.slice(0,6).map(a=>`<button data-app="${a.id}"><span>${a.icon}</span>${a.name}</button>`).join('')}</div></div><div class="dock"></div><div class="overlay" data-overlay hidden></div><aside class="panel" data-panel hidden></aside><div class="toast-region" aria-live="polite"></div>`;renderDock();wireShell();tick();clock=window.setInterval(tick,1000);}
function applySettings(s:Settings){const root=document.documentElement,theme=s.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):s.theme;root.dataset.theme=theme;root.dataset.wallpaper=s.wallpaper;root.dataset.motion=s.reducedMotion?'none':s.animation;root.style.setProperty('--accent',s.accent);root.style.fontSize=`${s.fontScale*16}px`;root.dataset.dock=s.dockPosition;}
function tick(){const e=document.querySelector('[data-clock]');if(e)e.textContent=new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',weekday:'short'}).format(new Date());}
function renderDock(){const dock=document.querySelector('.dock');if(!dock)return;const ids=['files','notes','terminal','settings'];dock.innerHTML=ids.map(id=>{const a=state.apps.find(x=>x.id===id)!;return`<button data-app="${id}" class="${state.windows.some(w=>w.app.id===id)?'running':''}" title="${a.name}">${a.icon}</button>`;}).join('')+`<i></i>${state.windows.map(w=>`<button data-window="${w.id}" title="${w.app.name}">${w.app.icon}</button>`).join('')}`;}
function wireShell(){document.addEventListener('click',async e=>{const t=e.target as HTMLElement,appButton=t.closest<HTMLElement>('[data-app]');if(appButton){const app=state.apps.find(a=>a.id===appButton.dataset.app);if(app){const win=await openWindow(app);wireApp(win,app.id);renderDock();}return;}const wb=t.closest<HTMLElement>('[data-window]');if(wb){const w=state.windows.find(x=>x.id===wb.dataset.window);if(w){w.element.hidden=false;focus(w.id);}return;}if(t.closest('[data-command]'))showCommand();if(t.closest('[data-quick]'))showQuick();if(t.closest('[data-notifications]'))showNotifications();});document.addEventListener('windows-changed',renderDock);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showCommand();}if(e.altKey&&e.key==='Tab'){e.preventDefault();const i=state.windows.findIndex(w=>w.id===state.active),w=state.windows[(i+1)%state.windows.length];if(w){w.element.hidden=false;focus(w.id);}}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='w'){e.preventDefault();closeActive();}});}
function panel(html:string){const p=document.querySelector<HTMLElement>('[data-panel]')!;p.innerHTML=html;p.hidden=false;document.querySelector<HTMLElement>('[data-overlay]')!.hidden=false;document.querySelector<HTMLElement>('[data-overlay]')!.onclick=()=>{p.hidden=true;document.querySelector<HTMLElement>('[data-overlay]')!.hidden=true;};return p;}
function showCommand(){const p=panel(`<h2>Open anything</h2><input class="command-input" autofocus placeholder="Search applications"><div data-results>${state.apps.map(a=>`<button data-app="${a.id}"><b>${a.icon} ${a.name}</b><small>${a.description}</small></button>`).join('')}</div><small>Ctrl K to open · Ctrl W to close a window</small>`),input=p.querySelector('input')!;input.focus();input.oninput=()=>p.querySelectorAll<HTMLElement>('[data-results] button').forEach(b=>b.hidden=!b.textContent!.toLowerCase().includes(input.value.toLowerCase()));}
async function showNotifications(){const rows:any[]=await api('/notifications');panel(`<h2>Notifications</h2>${rows.length?rows.map(n=>`<article class="notification"><b>${n.title}</b><p>${n.message}</p><button data-dismiss="${n.id}">Dismiss</button></article>`).join(''):'<p>All caught up.</p>'}`).onclick=async e=>{const id=(e.target as HTMLElement).dataset.dismiss;if(id){await api(`/notifications/${id}`,{method:'DELETE'});showNotifications();}};}
function showQuick(){const s=state.settings!;const p=panel(`<h2>Quick settings</h2><div class="quick"><button data-theme>${s.theme==='light'?'☀ Light':'◐ Dark'}</button><button data-motion>${s.reducedMotion?'Motion off':'Motion on'}</button><div><small>Storage & network</small><b>Local · Connected</b></div></div>`);p.querySelector<HTMLElement>('[data-theme]')!.onclick=()=>saveSettings({theme:s.theme==='light'?'dark':'light'});p.querySelector<HTMLElement>('[data-motion]')!.onclick=()=>saveSettings({reducedMotion:!s.reducedMotion});}
async function saveSettings(patch:Partial<Settings>){state.settings=await api('/settings',{method:'PUT',body:body(patch)});applySettings(state.settings!);document.querySelector<HTMLElement>('[data-panel]')!.hidden=true;document.querySelector<HTMLElement>('[data-overlay]')!.hidden=true;}
function toast(message:string){const e=document.createElement('div');e.className='toast';e.textContent=message;document.querySelector('.toast-region')!.append(e);setTimeout(()=>e.remove(),2600);}
function wireApp(win:HTMLElement,id:string){if(win.dataset.wired)return;win.dataset.wired='true';if(id==='editor'){const text=win.querySelector<HTMLTextAreaElement>('[data-editor]')!,doc=win.querySelector<HTMLInputElement>('[data-doc]')!,dirty=win.querySelector('[data-dirty]')!;text.oninput=()=>dirty.textContent='● Unsaved';win.querySelector<HTMLElement>('[data-action="save-doc"]')!.onclick=async()=>{await api('/fs/write',{method:'POST',body:body({path:doc.value,content:text.value})});dirty.textContent='Saved';toast('Document saved');};win.querySelector<HTMLElement>('[data-action="open-doc"]')!.onclick=async()=>{const r:any=await api('/fs/read',{method:'POST',body:body({path:doc.value})});text.value=r.content;dirty.textContent='';};win.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();(win.querySelector('[data-action="save-doc"]') as HTMLElement).click();}});}
if(id==='files')win.querySelectorAll<HTMLElement>('[data-file]').forEach(f=>f.onclick=async()=>{if(f.dataset.dir==='true')return toast('Folder navigation is available from the terminal');const r:any=await api('/fs/read',{method:'POST',body:body({path:f.dataset.file})});win.querySelector('.preview')!.textContent=r.content;});
if(id==='terminal'){const form=win.querySelector<HTMLFormElement>('[data-terminal]')!,out=win.querySelector<HTMLElement>('[data-output]')!;form.onsubmit=async e=>{e.preventDefault();const input=form.querySelector('input')!,cmd=input.value;input.value='';try{const result=await fileCommand(cmd);out.innerHTML=result==='__CLEAR__'?'':`${out.innerHTML}<pre>~ ${cmd}\n${result}</pre>`;}catch(error){out.innerHTML+=`<pre class="error">${(error as Error).message}</pre>`;}out.scrollTop=out.scrollHeight;};}
if(id==='calculator'){const input=win.querySelector<HTMLInputElement>('[data-expression]')!,result=win.querySelector('[data-result]')!,history=win.querySelector('[data-history]')!;win.querySelector<HTMLElement>('[data-action="calculate"]')!.onclick=()=>{try{if(!/^[\d\s+\-*/().%]+$/.test(input.value))throw 0;const value=Function(`"use strict";return (${input.value})`)();result.textContent=String(value);history.innerHTML=`<p>${input.value} = ${value}</p>`+history.innerHTML;}catch{result.textContent='Invalid expression';}};}
if(id==='notes'){let current:any={};const title=win.querySelector<HTMLInputElement>('[data-note-title]')!,folder=win.querySelector<HTMLInputElement>('[data-note-folder]')!,text=win.querySelector<HTMLTextAreaElement>('[data-note-body]')!;win.querySelectorAll<HTMLElement>('[data-note]').forEach(row=>row.onclick=()=>{current=JSON.parse(row.dataset.note!);title.value=current.title;folder.value=current.folder;text.value=current.body;});win.querySelector<HTMLElement>('[data-action="new-note"]')!.onclick=()=>{current={};title.value='';text.value='';title.focus();};const save=()=>{clearTimeout(noteTimer);noteTimer=window.setTimeout(async()=>{if(!title.value&&!text.value)return;current=await api('/notes',{method:'POST',body:body({...current,title:title.value||'Untitled',folder:folder.value,body:text.value})});toast('Note saved');},600);};title.oninput=folder.oninput=text.oninput=save;}
if(id==='settings')win.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-setting]').forEach(control=>{const key=control.dataset.setting as keyof Settings;const value=state.settings![key];if(control instanceof HTMLInputElement&&control.type==='checkbox')control.checked=Boolean(value);else control.value=String(value);control.onchange=()=>saveSettings({[key]:control instanceof HTMLInputElement&&control.type==='checkbox'?control.checked:control.type==='range'?Number(control.value):control.value} as any);});if(id==='wallpapers')win.querySelectorAll<HTMLElement>('[data-wallpaper]').forEach(w=>w.onclick=()=>saveSettings({wallpaper:w.dataset.wallpaper!}));}
boot().catch(error=>{os.innerHTML=`<div class="boot-error"><h1>FluidaOS could not start</h1><p>${error.message}</p></div>`;});
