import type {ShellSession,Workspace} from '../../shared/types/domain.js';
import {api,body} from '../core/api.js'; import {state,activeWorkspace} from '../core/state.js';
const changed=()=>document.dispatchEvent(new CustomEvent('workspace-changed'));
let saveQueue:Promise<void>=Promise.resolve(),pendingSnapshot:string|undefined;
export async function restoreSession(hydrate?:()=>void|Promise<void>){state.session=await api<ShellSession>('/shell/session');await hydrate?.();return state.session;}
export function persistSession(){if(!state.session)return;pendingSnapshot=body(structuredClone(state.session));window.clearTimeout(state.saveTimer);state.saveTimer=window.setTimeout(()=>{const snapshot=pendingSnapshot;if(!snapshot)return;pendingSnapshot=undefined;saveQueue=saveQueue.catch(()=>undefined).then(()=>api('/shell/session',{method:'PUT',body:snapshot}).then(()=>undefined)).catch(console.error);},200);}
export function createWorkspace(name='Workspace'){const workspace:Workspace={id:crypto.randomUUID(),name:name.trim()||'Workspace',windows:[],zIndexSequence:10,layout:'freeform',shortcutPositions:{}};state.session!.workspaces.push(workspace);switchWorkspace(workspace.id);return workspace;}
export function renameWorkspace(id:string,name:string){const workspace=state.session!.workspaces.find(item=>item.id===id);if(!workspace)throw new Error('Workspace not found');workspace.name=name.trim()||workspace.name;persistSession();changed();}
export function switchWorkspace(id:string){if(!state.session!.workspaces.some(item=>item.id===id))throw new Error('Workspace not found');const workspace=document.querySelector<HTMLElement>('.workspace');workspace?.classList.remove('workspace-entering');state.session!.activeWorkspaceId=id;for(const runtime of state.runtime.values()){runtime.element.hidden=!activeWorkspace().windows.some(window=>window.id===runtime.id)||runtime.model.minimized;if(!runtime.element.hidden)runtime.element.classList.add('window-restoring');}if(workspace){void workspace.offsetWidth;workspace.classList.add('workspace-entering');window.setTimeout(()=>workspace.classList.remove('workspace-entering'),400);}persistSession();changed();}
export function deleteWorkspace(id:string){const session=state.session!;if(session.workspaces.length===1)throw new Error('The last workspace cannot be deleted');const workspace=session.workspaces.find(item=>item.id===id);if(!workspace)throw new Error('Workspace not found');for(const item of workspace.windows){state.runtime.get(item.id)?.element.remove();state.runtime.delete(item.id);}session.workspaces=session.workspaces.filter(item=>item.id!==id);if(session.activeWorkspaceId===id)session.activeWorkspaceId=session.workspaces[0].id;switchWorkspace(session.activeWorkspaceId);}
