import {api,body} from '../core/api.js';
import type {ArchiveRecord,CalendarEvent,ClockState,FileEntry,InstalledApp} from '../../shared/types/domain.js';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const size=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
export function fileRows(files:FileEntry[],view:'grid'|'list'){return files.map(file=>`<button class="file" data-file="${esc(file.path)}" data-dir="${file.isDirectory}" aria-pressed="false"><b>${file.isDirectory?'▰':'▤'}</b><span>${esc(file.name)}</span><small>${file.isDirectory?'Folder':size(file.size)} · ${new Date(file.modifiedAt).toLocaleDateString()}</small></button>`).join('')||'<div class="empty-state">This folder is empty.</div>';}
export async function renderApp(id:string):Promise<string>{
 if(id==='files')return `<div class="files-app" data-files-view><div class="toolbar file-toolbar"><button data-action="up">← Up</button><nav data-breadcrumbs aria-label="Current folder"></nav><button data-action="new-file">New file</button><button data-action="new-folder">New folder</button><button data-action="rename">Rename</button><button data-action="copy">Copy</button><button data-action="move">Move</button><button data-action="delete">Delete</button><input data-file-search type="search" placeholder="Search files"><select data-file-sort aria-label="Sort"><option value="name">Name</option><option value="modified">Modified</option><option value="size">Size</option></select><button data-action="toggle-view">Grid/List</button></div><div class="file-status" data-file-status>Loading…</div><div class="file-grid" data-file-list aria-live="polite"></div><aside class="file-details"><pre class="preview" data-file-preview>Select a file to preview it.</pre></aside></div>`;
 if(id==='editor')return `<div class="toolbar"><input data-doc placeholder="Documents/untitled.txt"><button data-action="open-doc">Open</button><button data-action="save-doc">Save</button><span data-dirty></span></div><textarea class="editor" data-editor spellcheck="false" placeholder="Start writing…"></textarea>`;
 if(id==='notes'){const notes:any[]=await api('/notes');return `<div class="split"><aside><input data-note-search placeholder="Search notes"><button data-action="new-note">＋ New note</button><div data-note-list>${notes.map(note=>`<button class="note-row" data-note='${esc(JSON.stringify(note))}'><b>${esc(note.title)}</b><small>${esc(note.folder)}</small></button>`).join('')}</div></aside><section><input data-note-title placeholder="Note title"><input data-note-folder value="Notes"><textarea data-note-body class="editor" placeholder="Write a note…"></textarea><small data-note-status>Changes auto-save</small></section></div>`;}
 if(id==='terminal')return `<div class="terminal"><div data-output>FluidaOS restricted terminal — type <b>help</b>.</div><form data-terminal><span data-prompt>/</span><input autocomplete="off" autofocus aria-label="Command"></form></div>`;
 if(id==='calculator')return `<div class="calculator"><input data-expression placeholder="(24 * 7) / 3"><button data-action="calculate">Calculate</button><strong data-result>0</strong><div data-history></div></div>`;
 if(id==='monitor'){const snapshot:any=await api('/system');return `<div class="stats"><article><small>Storage</small><b>${snapshot.storage.files} files</b><span>${snapshot.storage.bytes.toLocaleString()} bytes</span></article><article><small>Installed apps</small><b>${snapshot.apps}</b></article><article><small>Runtime</small><b>${esc(snapshot.platform)}</b><span>${Math.round(snapshot.uptime)}s uptime</span></article><article><small>Session</small><b data-window-count></b><span>${esc(navigator.platform)}</span></article></div>`;}
 if(id==='settings')return `<div class="settings settings-app"><nav>${['Appearance','Accessibility','Desktop','Notifications','Storage','Applications','System'].map(section=>`<button data-settings-section="${section.toLowerCase()}">${section}</button>`).join('')}</nav><div><section data-section="appearance"><h3>Appearance</h3><label>Theme<select data-setting="theme"><option>dark</option><option>light</option><option>system</option></select></label><label>Accent<input type="color" data-setting="accent"></label><label>Wallpaper<select data-setting="wallpaper"><option>aurora</option><option>ember</option><option>lagoon</option><option>dusk</option></select></label><label>Font scale<input type="range" min="0.8" max="1.4" step="0.1" data-setting="fontScale"></label></section><section data-section="accessibility"><h3>Accessibility</h3><label>Animation<select data-setting="animation"><option>full</option><option>reduced</option><option>none</option></select></label><label><input type="checkbox" data-setting="reducedMotion"> Reduced motion</label><label><input type="checkbox" data-setting="accessibility.highContrast"> High contrast</label><label><input type="checkbox" data-setting="accessibility.focusVisible"> Strong focus indicators</label><label>Text scale<input type="range" min="0.8" max="2" step="0.1" data-setting="accessibility.textScale"></label></section><section data-section="desktop"><h3>Desktop</h3><label>Dock<select data-setting="dockPosition"><option>bottom</option><option>left</option><option>right</option></select></label><label>Workspace startup<select data-setting="desktop.workspaceBehavior"><option value="restore">Restore</option><option value="fresh">Fresh</option></select></label><label>Shortcut layout<select data-setting="desktop.shortcutLayout"><option>grid</option><option>list</option></select></label><label><input type="checkbox" data-setting="desktop.dockAutoHide"> Auto-hide dock</label><label>Clock<select data-setting="desktop.clockFormat"><option value="12h">12 hour</option><option value="24h">24 hour</option></select></label></section><section data-section="notifications"><h3>Notifications</h3>${['enabled','sound','showPreviews','doNotDisturb'].map(key=>`<label>${esc(key)}<input type="checkbox" data-setting="notifications.${key}"></label>`).join('')}</section><section data-section="storage"><h3>Storage</h3><div data-storage>Loading usage…</div><label>Files view<select data-setting="filesView"><option>grid</option><option>list</option></select></label></section><section data-section="applications"><h3>Applications</h3><label>Text files<input data-setting="defaultApps.text"></label><label>Images<input data-setting="defaultApps.images"></label></section><section data-section="system"><h3>System</h3><button data-action="reset-settings">Reset all settings</button><div data-system-info></div></section></div></div>`;
 if(id==='wallpapers')return `<div class="wallpapers">${['aurora','ember','lagoon','dusk'].map(value=>`<button data-wallpaper="${value}" class="wallpaper ${value}"><span>${value}</span></button>`).join('')}</div>`;
 if(id==='clock'){const state=await api<ClockState>('/app-state/clock');return `<div class="clock-app" data-clock-state='${esc(JSON.stringify(state))}'><h2 data-local-clock></h2><section><h3>World clocks</h3><div data-world-clocks>${state.worldClocks.map(zone=>`<p><b>${esc(zone)}</b> <span data-zone="${esc(zone)}"></span></p>`).join('')}</div><input data-zone-input placeholder="Europe/London"><button data-action="add-zone">Add</button></section><section><h3>Alarms</h3><input type="time" data-alarm-time><input data-alarm-label placeholder="Alarm label"><button data-action="add-alarm">Add alarm</button><div data-alarms>${state.alarms.map(alarm=>`<p>${esc(alarm.time)} ${esc(alarm.label)}</p>`).join('')}</div></section><section><h3>Timer</h3><input type="number" min="0" data-timer value="${state.timerSeconds}"><button data-action="save-clock">Save state</button></section><section><h3>Stopwatch</h3><b data-stopwatch>${state.stopwatchSeconds}s</b><button data-action="toggle-stopwatch">${state.stopwatchRunning?'Pause':'Start'}</button><button data-action="reset-stopwatch">Reset</button></section></div>`;}
 if(id==='calendar'){const state=await api<{events:CalendarEvent[]}>('/app-state/calendar'),today=new Date().toISOString().slice(0,10);return `<div class="calendar-app" data-calendar-state='${esc(JSON.stringify(state))}'><div class="toolbar"><button data-action="previous-month">←</button><input type="month" data-calendar-month value="${today.slice(0,7)}"><button data-action="next-month">→</button></div><div data-calendar-grid></div><h3>Agenda</h3><div data-agenda></div><input type="date" data-event-date value="${today}"><input data-event-title placeholder="Event title"><textarea data-event-details placeholder="Details"></textarea><button data-action="add-event">Add event</button></div>`;}
 if(id==='photos'){const photos:FileEntry[]=await api('/photos');return `<div class="photos-app"><div class="photo-grid">${photos.map(photo=>`<button data-photo="${esc(photo.path)}"><img src="/api/fs/download?path=${encodeURIComponent(photo.path)}" alt="${esc(photo.name)}" loading="lazy"><span>${esc(photo.name)}</span></button>`).join('')||'<div class="empty-state">No images in storage.</div>'}</div><div data-photo-details>Select a photo for safe metadata preview.</div></div>`;}
 if(id==='archive'){const state=await api<{records:ArchiveRecord[]}>('/app-state/archive');return `<div class="archive-app" data-archive-state='${esc(JSON.stringify(state))}'><p>Archive records organize paths only. Content is never executed or unpacked.</p><input data-archive-name placeholder="Archive name"><input data-archive-paths placeholder="Comma-separated storage paths"><button data-action="add-archive">Create record</button><div data-archives>${state.records.map(record=>`<article><b>${esc(record.name)}</b><small>${record.paths.map(esc).join(', ')}</small></article>`).join('')}</div></div>`;}
 if(id==='app-center'){const apps=await api<InstalledApp[]>('/apps/all');return `<div class="app-center">${apps.map(app=>`<article><b>${esc(app.manifest.icon)} ${esc(app.manifest.name)}</b><p>${esc(app.manifest.description)}</p><small>v${esc(app.manifest.version)} · ${app.source.kind}</small><label><input type="checkbox" data-toggle-app="${esc(app.manifest.id)}" ${app.enabled?'checked':''}> Enabled</label></article>`).join('')}</div>`;}
 return '<p>Application unavailable.</p>';
}
let terminalDirectory='';
export async function fileCommand(command:string){const trimmed=command.trim();if(trimmed==='clear')return'__CLEAR__';const result=await api<{stdout:string;stderr:string;cwd:string}>('/terminal/jobs',{method:'POST',body:body({command,cwd:terminalDirectory})});terminalDirectory=result.cwd;return result.stdout||result.stderr||'Done.';}
