import fs from 'node:fs/promises';
import {mkdirSync,realpathSync} from 'node:fs';
import path from 'node:path';
import type {AppCapability,AppManifest,InstalledApp} from '../../shared/types/domain.js';
import {JsonRepository} from './jsonRepository.js';
const capabilities=new Set<AppCapability>(['files:read','files:write','terminal','notifications','system:read']);
const validation=(message:string)=>Object.assign(new Error(message),{status:400,code:'INVALID_MANIFEST'});
export class AppRegistryService {
 private repository:JsonRepository<InstalledApp[]>;
 constructor(private registryRoot=path.resolve(process.cwd(),'app_packages'),dataRoot=path.resolve(process.cwd(),'os_storage/.fluida'),private builtins:InstalledApp[]=[]){const resolved=path.resolve(registryRoot);mkdirSync(resolved,{recursive:true});this.registryRoot=realpathSync.native(resolved);this.repository=new JsonRepository(path.join(dataRoot,'apps.json'),[]);}
 validate(value:unknown):AppManifest{if(!value||typeof value!=='object')throw validation('Manifest must be an object');const row=value as Record<string,unknown>;for(const key of ['id','name','icon','description','version','entryPoint'])if(typeof row[key]!=='string'||!row[key])throw validation(`Invalid ${key}`);if(!/^[a-z0-9][a-z0-9-]{1,63}$/.test(row.id as string))throw validation('Invalid application ID');if(!Array.isArray(row.capabilities)||row.capabilities.some(item=>typeof item!=='string'||!capabilities.has(item as AppCapability)))throw validation('Invalid capabilities');return row as unknown as AppManifest;}
 private contained(root:string,target:string){return target===root||target.startsWith(`${root}${path.sep}`);}
 private canonicalPath(root:string,target:string,message:string){const parent=realpathSync.native(path.dirname(target));const canonical=realpathSync.native(target);if(!this.contained(root,parent)||!this.contained(root,canonical))throw validation(message);return canonical;}
 private packagePath(relative:string){if(path.isAbsolute(relative)||relative.includes('\0'))throw validation('Invalid package path');const target=path.resolve(this.registryRoot,relative);if(!this.contained(this.registryRoot,target))throw validation('Package escapes registry root');return this.canonicalPath(this.registryRoot,target,'Package escapes registry root');}
 async list(){return[...this.builtins,...await this.repository.read()];}
 async install(packagePath:string){const directory=this.packagePath(packagePath),manifestPath=this.canonicalPath(directory,path.join(directory,'manifest.json'),'Manifest escapes package'),manifest=this.validate(JSON.parse(await fs.readFile(manifestPath,'utf8')));if(path.isAbsolute(manifest.entryPoint)||manifest.entryPoint.includes('\0'))throw validation('Entry point escapes package');const unresolvedEntry=path.resolve(directory,manifest.entryPoint);if(!this.contained(directory,unresolvedEntry))throw validation('Entry point escapes package');const entry=this.canonicalPath(directory,unresolvedEntry,'Entry point escapes package');if(!(await fs.stat(entry)).isFile())throw validation('Entry point is not a file');const application:InstalledApp={manifest,source:{kind:'local',packagePath},enabled:true,installedAt:new Date().toISOString()};await this.repository.update(local=>{if(this.builtins.some(app=>app.manifest.id===manifest.id)||local.some(app=>app.manifest.id===manifest.id))throw Object.assign(new Error('Application ID already installed'),{status:409,code:'DUPLICATE_APP'});local.push(application);return local;});return application;}
 async setEnabled(id:string,enabled:boolean){let application:InstalledApp|undefined;await this.repository.update(rows=>{application=rows.find(row=>row.manifest.id===id);if(!application)throw Object.assign(new Error('Application not found'),{status:404,code:'NOT_FOUND'});application.enabled=enabled;return rows;});return application!;}
 async uninstall(id:string){await this.repository.update(rows=>{const next=rows.filter(row=>row.manifest.id!==id);if(next.length===rows.length)throw Object.assign(new Error('Application not found'),{status:404,code:'NOT_FOUND'});return next;});}
}
