import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {JsonRepository} from './jsonRepository.js';
import type {AppDefinition,AppStateMap,Note,Notification,Settings,ShellSession} from '../../shared/types/domain.js';

export const defaultSettings:Settings={theme:'dark',accent:'#7c6cff',wallpaper:'aurora',fontScale:1,dockPosition:'bottom',animation:'full',reducedMotion:false,volume:70,brightness:100,filesView:'grid',notifications:{enabled:true,sound:true,showPreviews:true,doNotDisturb:false},accessibility:{highContrast:false,focusVisible:true,textScale:1},desktop:{workspaceBehavior:'restore',shortcutLayout:'grid',dockAutoHide:false,clockFormat:'24h'},defaultApps:{text:'editor',images:'photos'}};
const normalizeSettings=(value:Partial<Settings>):Settings=>({...defaultSettings,...value,notifications:{...defaultSettings.notifications,...value.notifications},accessibility:{...defaultSettings.accessibility,...value.accessibility},desktop:{...defaultSettings.desktop,...value.desktop},defaultApps:{...defaultSettings.defaultApps,...value.defaultApps}});
export const defaultSession:ShellSession={id:'local',activeWorkspaceId:'workspace-1',pinnedApplications:['files','notes','terminal','clock','calendar','settings'],updatedAt:new Date(0).toISOString(),workspaces:[{id:'workspace-1',name:'Main',windows:[],zIndexSequence:10,layout:'freeform'}]};
const defaultAppState:AppStateMap={clock:{worldClocks:['UTC'],alarms:[],timerSeconds:300,stopwatchSeconds:0,stopwatchRunning:false},calendar:{events:[]},archive:{records:[]}};
const catalog:[string,string,string,string][]=[['files','Files','▰','Browse and manage local files'],['editor','Editor','✎','Edit plain-text documents'],['notes','Notes','◫','Capture persistent notes'],['terminal','Terminal','›_','Run 20 contained commands'],['monitor','Monitor','⌁','Inspect this session'],['calculator','Calculator','＋','Calculate with history'],['settings','Settings','⚙','Personalize FluidaOS'],['wallpapers','Wallpapers','◉','Choose a desktop background'],['clock','Clock','◷','World clocks, alarms, timers, and stopwatch'],['calendar','Calendar','▦','Local calendar and agenda'],['photos','Photos','▧','Storage-backed image gallery'],['archive','Archive Manager','▣','Organize safe archive records'],['app-center','App Center','⬡','Manage installed applications']];

export class DataService {
 settings:JsonRepository<Settings>;notes:JsonRepository<Note[]>;notifications:JsonRepository<Notification[]>;session:JsonRepository<ShellSession>;appState:JsonRepository<AppStateMap>;
 readonly apps:AppDefinition[]=catalog.map(([id,name,icon,description])=>({id,name,icon,description}));
 constructor(private root=path.resolve(process.cwd(),'os_storage/.fluida')){this.settings=new JsonRepository(path.join(root,'settings.json'),defaultSettings);this.notes=new JsonRepository(path.join(root,'notes.json'),[]);this.notifications=new JsonRepository(path.join(root,'notifications.json'),[{id:'welcome',title:'Welcome to FluidaOS',message:'Your workspace is ready.',read:false,createdAt:new Date().toISOString()}]);this.session=new JsonRepository(path.join(root,'session.json'),defaultSession);this.appState=new JsonRepository(path.join(root,'app-state.json'),defaultAppState);}
 async readSettings(){const normalized=normalizeSettings(await this.settings.read());await this.settings.write(normalized);return normalized;}
 async saveSettings(patch:Partial<Settings>){const current=await this.readSettings();return this.settings.write(normalizeSettings({...current,...patch,notifications:{...current.notifications,...patch.notifications},accessibility:{...current.accessibility,...patch.accessibility},desktop:{...current.desktop,...patch.desktop},defaultApps:{...current.defaultApps,...patch.defaultApps}}));}
 resetSettings(){return this.settings.write(structuredClone(defaultSettings));}
 async saveSession(value:ShellSession){if(!value.workspaces.length||!value.workspaces.some(workspace=>workspace.id===value.activeWorkspaceId))throw Object.assign(new Error('Invalid shell session'),{status:400,code:'VALIDATION_ERROR'});return this.session.write({...value,updatedAt:new Date().toISOString()});}
 async saveNote(input:Partial<Note>&{title:string;body:string}){const notes=await this.notes.read(),now=new Date().toISOString(),index=input.id?notes.findIndex(n=>n.id===input.id):-1;const note:Note={id:input.id||randomUUID(),title:input.title,body:input.body,folder:input.folder||'Notes',updatedAt:now};if(index>=0)notes[index]=note;else notes.unshift(note);await this.notes.write(notes);return note;}
 async readAppState<K extends keyof AppStateMap>(app:K){return (await this.appState.read())[app];}
 async saveAppState<K extends keyof AppStateMap>(app:K,value:AppStateMap[K]){const state=await this.appState.read();state[app]=value;await this.appState.write(state);return value;}
}
