import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {JsonRepository} from './jsonRepository.js';
import type {AppDefinition,Note,Notification,Settings,ShellSession} from '../../shared/types/domain.js';

export const defaultSettings:Settings={theme:'dark',accent:'#7c6cff',wallpaper:'aurora',fontScale:1,dockPosition:'bottom',animation:'full',reducedMotion:false,volume:70,brightness:100,filesView:'grid',notifications:{enabled:true,sound:true,showPreviews:true,doNotDisturb:false,quietHours:false},accessibility:{highContrast:false,focusVisible:true,textScale:1},desktop:{workspaceBehavior:'independent',shortcutLayout:'grid',dockAutoHide:false,clockFormat:'24'},defaultApplications:{text:'editor',image:'photos'}};
export const defaultSession:ShellSession={id:'local',activeWorkspaceId:'workspace-1',pinnedApplications:['files','notes','terminal','settings'],updatedAt:new Date(0).toISOString(),workspaces:[{id:'workspace-1',name:'Main',windows:[],zIndexSequence:10,layout:'freeform'}]};
const app=(id:string,name:string,icon:string,description:string):AppDefinition=>({id,name,icon,description});
export class DataService {
 settings:JsonRepository<Settings>; notes:JsonRepository<Note[]>; notifications:JsonRepository<Notification[]>; session:JsonRepository<ShellSession>;
 readonly apps:AppDefinition[]=[app('files','Files','▰','Browse and manage local files'),app('editor','Editor','✎','Edit plain-text documents'),app('notes','Notes','◫','Capture persistent notes'),app('terminal','Terminal','›_','Run safe OS commands'),app('monitor','Monitor','⌁','Inspect this session'),app('calculator','Calculator','＋','Calculate with history'),app('settings','Settings','⚙','Personalize FluidaOS'),app('wallpapers','Wallpapers','◉','Choose a desktop background'),app('clock','Clock','◷','World clocks, alarms, timers, and stopwatch'),app('calendar','Calendar','▦','Local calendar and agenda'),app('photos','Photos','▧','Storage-backed image gallery'),app('archives','Archive Manager','▤','Organize safe archive records'),app('app-center','App Center','⬡','Manage installed applications')];
 constructor(root=path.resolve(process.cwd(),'os_storage/.fluida')){this.settings=new JsonRepository(path.join(root,'settings.json'),defaultSettings);this.notes=new JsonRepository(path.join(root,'notes.json'),[]);this.notifications=new JsonRepository(path.join(root,'notifications.json'),[{id:'welcome',title:'Welcome to FluidaOS',message:'Your workspace is ready.',read:false,createdAt:new Date().toISOString()}]);this.session=new JsonRepository(path.join(root,'session.json'),defaultSession);}
 async saveSettings(patch:Partial<Settings>){const current=await this.settings.read();return this.settings.write({...current,...patch,notifications:{...current.notifications,...patch.notifications},accessibility:{...current.accessibility,...patch.accessibility},desktop:{...current.desktop,...patch.desktop},defaultApplications:{...current.defaultApplications,...patch.defaultApplications}});}
 async resetSettings(){return this.settings.write(structuredClone(defaultSettings));}
 async saveSession(value:ShellSession){if(!value.workspaces.length||!value.workspaces.some(workspace=>workspace.id===value.activeWorkspaceId))throw Object.assign(new Error('Invalid shell session'),{status:400,code:'VALIDATION_ERROR'});return this.session.write({...value,updatedAt:new Date().toISOString()});}
 async saveNote(input:Partial<Note>&{title:string;body:string}){const notes=await this.notes.read(),now=new Date().toISOString(),index=input.id?notes.findIndex(n=>n.id===input.id):-1;const note:Note={id:input.id||randomUUID(),title:input.title,body:input.body,folder:input.folder||'Notes',updatedAt:now};if(index>=0)notes[index]=note;else notes.unshift(note);await this.notes.write(notes);return note;}
}
