import fs from 'node:fs/promises';
import path from 'node:path';
import type {FileEntry} from '../../shared/types/domain.js';
const invalid=(message:string)=>Object.assign(new Error(message),{status:400,code:'INVALID_PATH'});
export class FileService {
 readonly root:string; constructor(root=path.resolve(process.cwd(),'os_storage')){this.root=path.resolve(root);}
 resolve(userPath=''){if(typeof userPath!=='string'||path.isAbsolute(userPath)||userPath.includes('\0'))throw invalid('Invalid storage path');const target=path.resolve(this.root,userPath);if(target!==this.root&&!target.startsWith(`${this.root}${path.sep}`))throw invalid('Path escapes OS storage');return target;}
 relative(absolute:string){const value=path.relative(this.root,absolute);if(value.startsWith('..')||path.isAbsolute(value))throw invalid('Path escapes OS storage');return value.split(path.sep).join('/');}
 async list(relative=''):Promise<FileEntry[]>{const target=this.resolve(relative);await fs.mkdir(target,{recursive:true});const entries=await fs.readdir(target,{withFileTypes:true});return Promise.all(entries.map(async entry=>{const item=path.join(target,entry.name),stat=await fs.stat(item);return{name:entry.name,path:this.relative(item),isDirectory:entry.isDirectory(),size:entry.isDirectory()?0:stat.size,modifiedAt:stat.mtime.toISOString()};})).then(rows=>rows.sort((a,b)=>Number(b.isDirectory)-Number(a.isDirectory)||a.name.localeCompare(b.name)));}
 async read(relative:string){return fs.readFile(this.resolve(relative),'utf8');} async write(relative:string,content:string){await this.writeBuffer(relative,Buffer.from(content));} async writeBuffer(relative:string,content:Buffer){const target=this.resolve(relative);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content);} async mkdir(relative:string){await fs.mkdir(this.resolve(relative),{recursive:false});} async rename(from:string,to:string){const target=this.resolve(to);await fs.mkdir(path.dirname(target),{recursive:true});await fs.rename(this.resolve(from),target);} async delete(relative:string){const target=this.resolve(relative);if(target===this.root)throw invalid('Storage root cannot be deleted');await fs.rm(target,{recursive:true});}
 normalizeFilename(name:string){const normalized=path.basename(name).replace(/[^\p{L}\p{N}._ -]/gu,'_').trim();if(!normalized||normalized==='.'||normalized==='..')throw invalid('Invalid filename');return normalized;}
 async importBase64(directory:string,name:string,value:string,maxBytes=5*1024*1024){const content=Buffer.from(value,'base64');if(content.length>maxBytes)throw Object.assign(new Error('Upload exceeds size limit'),{status:413,code:'UPLOAD_TOO_LARGE'});const relative=path.posix.join(directory.replaceAll('\\','/'),this.normalizeFilename(name));await this.writeBuffer(relative,content);return (await this.list(directory)).find(entry=>entry.path===relative)!;}
 async usage(){let bytes=0,files=0;const walk=async(dir:string):Promise<void>=>{for(const entry of await fs.readdir(dir,{withFileTypes:true}).catch(()=>[])){const item=path.join(dir,entry.name);if(entry.isDirectory())await walk(item);else{bytes+=(await fs.stat(item)).size;files++;}}};await walk(this.root);return{bytes,files};}
}
