import fs from 'node:fs/promises';
import path from 'node:path';
import type {FileEntry,FilePreview,FileSearchResult} from '../../shared/types/domain.js';
const invalid=(message:string)=>Object.assign(new Error(message),{status:400,code:'INVALID_PATH'});
const mime=(name:string)=>({'.txt':'text/plain','.md':'text/markdown','.json':'application/json','.js':'text/javascript','.ts':'text/typescript','.css':'text/css','.html':'text/html','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.svg':'image/svg+xml'}[path.extname(name).toLowerCase()]??'application/octet-stream');
export class FileService {
 readonly root:string;
 constructor(root=path.resolve(process.cwd(),'os_storage')){this.root=path.resolve(root);}
 resolve(userPath=''){if(typeof userPath!=='string'||path.isAbsolute(userPath)||userPath.includes('\0'))throw invalid('Invalid storage path');const target=path.resolve(this.root,userPath.replaceAll('\\','/'));if(target!==this.root&&!target.startsWith(`${this.root}${path.sep}`))throw invalid('Path escapes OS storage');return target;}
 relative(absolute:string){const value=path.relative(this.root,absolute);if(value.startsWith('..')||path.isAbsolute(value))throw invalid('Path escapes OS storage');return value.split(path.sep).join('/');}
 private async entry(absolute:string):Promise<FileEntry>{const stat=await fs.stat(absolute);return{name:path.basename(absolute),path:this.relative(absolute),isDirectory:stat.isDirectory(),size:stat.isDirectory()?0:stat.size,modifiedAt:stat.mtime.toISOString(),mimeType:stat.isDirectory()?'inode/directory':mime(absolute)};}
 async list(relative=''):Promise<FileEntry[]>{const target=this.resolve(relative);await fs.mkdir(target,{recursive:true});const rows=await Promise.all((await fs.readdir(target)).map(name=>this.entry(path.join(target,name))));return rows.sort((a,b)=>Number(b.isDirectory)-Number(a.isDirectory)||a.name.localeCompare(b.name));}
 async metadata(relative:string){return this.entry(this.resolve(relative));}
 async preview(relative:string,maxBytes=128*1024):Promise<FilePreview>{if(!Number.isInteger(maxBytes)||maxBytes<1||maxBytes>256*1024)throw invalid('Invalid preview limit');const target=this.resolve(relative),stat=await fs.stat(target);if(!stat.isFile())throw invalid('Preview path must be a file');const handle=await fs.open(target,'r');try{const length=Math.min(stat.size,maxBytes),buffer=Buffer.alloc(length);await handle.read(buffer,0,length,0);return{path:this.relative(target),content:buffer.toString('utf8'),truncated:stat.size>length,size:stat.size,mimeType:mime(target)};}finally{await handle.close();}}
 async read(relative:string){return fs.readFile(this.resolve(relative),'utf8');}
 async write(relative:string,content:string){await this.writeBuffer(relative,Buffer.from(content));}
 async writeBuffer(relative:string,content:Buffer){const target=this.resolve(relative);if(target===this.root)throw invalid('Storage root cannot be overwritten');await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content);}
 async append(relative:string,content:string){const target=this.resolve(relative);await fs.mkdir(path.dirname(target),{recursive:true});await fs.appendFile(target,content);}
 async touch(relative:string){const target=this.resolve(relative);await fs.mkdir(path.dirname(target),{recursive:true});const handle=await fs.open(target,'a');await handle.close();const now=new Date();await fs.utimes(target,now,now);}
 async mkdir(relative:string){const target=this.resolve(relative);if(target===this.root)throw invalid('Directory path is required');await fs.mkdir(target,{recursive:false});}
 async rename(from:string,to:string){const source=this.resolve(from),target=this.resolve(to);if(source===this.root||target===this.root)throw invalid('Storage root cannot be moved');await fs.mkdir(path.dirname(target),{recursive:true});await fs.rename(source,target);}
 async copy(from:string,to:string){const source=this.resolve(from),target=this.resolve(to);if(source===this.root||target===this.root||target.startsWith(`${source}${path.sep}`))throw invalid('Invalid copy destination');await fs.mkdir(path.dirname(target),{recursive:true});await fs.cp(source,target,{recursive:true,errorOnExist:true,force:false});}
 async delete(relative:string,recursive=false){const target=this.resolve(relative);if(target===this.root)throw invalid('Storage root cannot be deleted');const stat=await fs.stat(target);if(stat.isDirectory()&&!recursive){if((await fs.readdir(target)).length)throw Object.assign(new Error('Directory is not empty; recursive confirmation is required'),{status:409,code:'DIRECTORY_NOT_EMPTY'});await fs.rmdir(target);}else await fs.rm(target,{recursive,force:false});}
 async search(directory:string,query:string,limit=200):Promise<FileSearchResult[]>{if(!query.trim()||query.length>128||!Number.isInteger(limit)||limit<1||limit>500)throw invalid('Invalid search');const root=this.resolve(directory),needle=query.toLocaleLowerCase(),results:FileSearchResult[]=[];const walk=async(current:string):Promise<void>=>{for(const name of await fs.readdir(current)){if(results.length>=limit)return;const absolute=path.join(current,name),entry=await this.entry(absolute);if(name.toLocaleLowerCase().includes(needle))results.push({...entry,parent:path.posix.dirname(entry.path)==='.'?'':path.posix.dirname(entry.path)});if(entry.isDirectory)await walk(absolute);}};await walk(root);return results;}
 normalizeFilename(name:string){const normalized=path.basename(name).replace(/[^\p{L}\p{N}._ -]/gu,'_').trim();if(!normalized||normalized==='.'||normalized==='..')throw invalid('Invalid filename');return normalized;}
 async importBase64(directory:string,name:string,value:string,maxBytes=5*1024*1024){if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value))throw invalid('Invalid base64 content');const content=Buffer.from(value,'base64');if(content.length>maxBytes)throw Object.assign(new Error('Upload exceeds size limit'),{status:413,code:'UPLOAD_TOO_LARGE'});const relative=path.posix.join(directory.replaceAll('\\','/'),this.normalizeFilename(name));await this.writeBuffer(relative,content);return this.metadata(relative);}
 async usage(){let bytes=0,files=0;const walk=async(dir:string):Promise<void>=>{for(const entry of await fs.readdir(dir,{withFileTypes:true}).catch(()=>[])){if(entry.name==='.fluida')continue;const item=path.join(dir,entry.name);if(entry.isDirectory())await walk(item);else{bytes+=(await fs.stat(item)).size;files++;}}};await walk(this.root);return{bytes,files};}
}
