import {randomUUID} from 'node:crypto';
import {spawn, type ChildProcessWithoutNullStreams} from 'node:child_process';
import path from 'node:path';
import type {TerminalJob,TerminalResult,TerminalJobState} from '../../shared/types/domain.js';
import {FileService} from './fileService.js';

interface ScriptRegistration { executable:string; args:string[] }
interface RunningJob { job:TerminalJob; process?:ChildProcessWithoutNullStreams; cancel?:()=>void }
const commandError=(message:string)=>Object.assign(new Error(message),{status:400,code:'TERMINAL_COMMAND_REJECTED'});
export class TerminalService {
 private jobs=new Map<string,RunningJob>();
 constructor(private files=new FileService(),private scripts:Record<string,ScriptRegistration>={},private timeoutMs=5000,private outputLimit=64*1024){}
 list(ownerId?:string){return [...this.jobs.values()].map(item=>item.job).filter(job=>!ownerId||job.ownerId===ownerId);}
 private tokenize(command:string){return command.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)?.map(value=>value.replace(/^(['"])(.*)\1$/,'$2'))??[];}
 private target(cwd:string,input=''){const candidate=path.posix.normalize(path.posix.join(cwd,input));if(candidate==='..'||candidate.startsWith('../'))throw commandError('Path escapes OS storage');const joined=candidate==='.'?'':candidate;this.files.resolve(joined);return joined;}
 async execute(ownerId:string,input:{command:string;cwd:string}):Promise<TerminalResult>{const started=Date.now(),tokens=this.tokenize(input.command),name=tokens.shift();if(!name)throw commandError('Command is required');const cwd=this.target('',input.cwd||'');const id=randomUUID(),job:TerminalJob={id,ownerId,command:input.command,cwd,state:{kind:'running'},startedAt:new Date().toISOString()};this.jobs.set(id,{job});try{let stdout='',nextCwd=cwd;if(name==='cd'){const destination=this.target(cwd,tokens[0]||'');const absolute=this.files.resolve(destination);const stat=await import('node:fs/promises').then(fs=>fs.stat(absolute));if(!stat.isDirectory())throw commandError('Not a directory');nextCwd=destination;}else if(name==='ls'){stdout=(await this.files.list(this.target(cwd,tokens[0]||''))).map(entry=>`${entry.isDirectory?'d':'-'} ${entry.name}`).join('\n');}else if(name==='mkdir'){if(!tokens[0])throw commandError('mkdir requires a path');await this.files.mkdir(this.target(cwd,tokens[0]));}else if(name==='rm'){if(!tokens[0])throw commandError('rm requires a path');await this.files.delete(this.target(cwd,tokens[0]));}else if(name==='touch'){if(!tokens[0])throw commandError('touch requires a path');await this.files.write(this.target(cwd,tokens[0]),'');}else if(name==='cat'){if(!tokens[0])throw commandError('cat requires a path');stdout=await this.files.read(this.target(cwd,tokens[0]));}else if(this.scripts[name])return await this.runScript(job,this.scripts[name],tokens,started);else throw commandError(`Command not allowed: ${name}`);return this.finish(job,{kind:'completed',exitCode:0},stdout,'',0,nextCwd,started);}catch(error){if(job.state.kind==='running'){const state:TerminalJobState={kind:'failed',exitCode:null,reason:(error as Error).message};this.finish(job,state,'',(error as Error).message,null,cwd,started);}throw error;}}
 private runScript(job:TerminalJob,registration:ScriptRegistration,args:string[],started:number){return new Promise<TerminalResult>((resolve,reject)=>{let stdout='',stderr='',settled=false,timer:ReturnType<typeof setTimeout>;const child=spawn(registration.executable,[...registration.args,...args],{cwd:this.files.resolve(job.cwd),shell:false,stdio:'pipe'});const settle=(state:TerminalJobState,exitCode:number|null,error?:Error)=>{if(settled)return false;settled=true;clearTimeout(timer);const result=this.finish(job,state,stdout,stderr,exitCode,job.cwd,started);if(error)reject(error);else resolve(result);return true;};const cancel=()=>{if(settle({kind:'cancelled'},null))child.kill();};this.jobs.set(job.id,{job,process:child,cancel});const append=(current:string,chunk:Buffer)=>{const next=current+chunk.toString();if(Buffer.byteLength(next)>this.outputLimit){const error=commandError('Command output limit exceeded');if(settle({kind:'failed',exitCode:null,reason:error.message},null,error))child.kill();return current;}return next;};child.stdout.on('data',chunk=>{stdout=append(stdout,chunk);});child.stderr.on('data',chunk=>{stderr=append(stderr,chunk);});timer=setTimeout(()=>{if(settle({kind:'timed-out'},null))child.kill();},this.timeoutMs);child.on('error',error=>{settle({kind:'failed',exitCode:null,reason:'Script process failed'},null,error);});child.on('close',code=>{settle(code===0?{kind:'completed',exitCode:0}:{kind:'failed',exitCode:code,reason:stderr||'Script failed'},code);});});}
 private finish(job:TerminalJob,state:TerminalJobState,stdout:string,stderr:string,exitCode:number|null,cwd:string,started:number):TerminalResult{job.state=state;job.finishedAt=new Date().toISOString();return{jobId:job.id,stdout,stderr,exitCode,duration:Date.now()-started,cwd,state};}
 terminate(ownerId:string,id:string){const running=this.jobs.get(id);if(!running)throw Object.assign(new Error('Terminal job not found'),{status:404,code:'NOT_FOUND'});if(running.job.ownerId!==ownerId)throw Object.assign(new Error('Terminal job belongs to another session'),{status:403,code:'FORBIDDEN'});if(running.job.state.kind!=='running')throw commandError('Terminal job is not running');if(running.cancel)running.cancel();else{running.job.state={kind:'cancelled'};running.job.finishedAt=new Date().toISOString();running.process?.kill();}return running.job;}
}
