import {cpSync,existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';

const apps=[
 ['files','Files','▰','Browse and manage local files',['files:read','files:write']],['editor','Editor','✎','Edit plain-text documents',['files:read','files:write']],['notes','Notes','◫','Capture persistent notes',['files:read','files:write']],['terminal','Terminal','›_','Run contained commands',['terminal']],['monitor','Monitor','⌁','Inspect this session',['system:read']],['calculator','Calculator','＋','Calculate with history',[]],['settings','Settings','⚙','Personalize FluidaOS',['system:read']],['wallpapers','Wallpapers','◉','Choose a desktop background',[]],['clock','Clock','◷','World clocks, alarms, timers, and stopwatch',[]],['calendar','Calendar','▦','Local calendar and agenda',[]],['photos','Photos','▧','Storage-backed image gallery',['files:read']],['archive','Archive Manager','▣','Organize safe archive records',['files:read']],['app-center','App Center','⬡','Manage installed applications',[]]
];
const sourceRoot='packages/apps',outputRoot='app_packages';
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
const crc32=data=>{let crc=0xffffffff;for(const byte of data)crc=crcTable[(crc^byte)&255]^(crc>>>8);return(crc^0xffffffff)>>>0};
function zip(files){let offset=0;const local=[],central=[];for(const[name,data]of files){const filename=Buffer.from(name),crc=crc32(data),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt32LE(crc,14);header.writeUInt32LE(data.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(filename.length,26);local.push(header,filename,data);const directory=Buffer.alloc(46);directory.writeUInt32LE(0x02014b50);directory.writeUInt16LE(0x0314,4);directory.writeUInt16LE(20,6);directory.writeUInt16LE(0x800,8);directory.writeUInt32LE(crc,16);directory.writeUInt32LE(data.length,20);directory.writeUInt32LE(data.length,24);directory.writeUInt16LE(filename.length,28);directory.writeUInt32LE((0o100644<<16)>>>0,38);directory.writeUInt32LE(offset,42);central.push(directory,filename);offset+=header.length+filename.length+data.length}const body=Buffer.concat(local),index=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(index.length,12);end.writeUInt32LE(body.length,16);return Buffer.concat([body,index,end])}
function initialize([id,name,icon,description,capabilities]){const directory=join(sourceRoot,id);if(existsSync(directory))return;mkdirSync(directory,{recursive:true});writeFileSync(join(directory,'manifest.json'),JSON.stringify({id,name,icon,description,version:'1.0.0',entryPoint:'app.js',capabilities},null,2)+'\n');writeFileSync(join(directory,'index.html'),'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{margin:0;padding:24px;background:#171823;color:#f7f7fb;font:15px system-ui}main{max-width:42rem}small{color:#aaaabd}</style></head><body><main id="app"></main><script src="app.js"></script></body></html>\n');writeFileSync(join(directory,'app.js'),`const manifest=${JSON.stringify({id,name,icon,description})};\nconst root=document.querySelector('#app');root.innerHTML='<h1>'+manifest.icon+' '+manifest.name+'</h1><p>'+manifest.description+'</p><small>Running in an isolated FluidaOS package.</small>';\nwindow.addEventListener('message',event=>{if(event.source!==parent||event.data?.fluida!==true||event.data?.type!=='init'||event.data?.appId!==manifest.id)return;document.documentElement.dataset.ready='true'});\n`)}
if(process.argv.includes('--init'))apps.forEach(initialize);
mkdirSync(join(outputRoot,'builtin'),{recursive:true});mkdirSync(join(outputRoot,'archives'),{recursive:true});
for(const [id]of apps){const directory=join(sourceRoot,id),required=['manifest.json','index.html','app.js'];for(const file of required)if(!existsSync(join(directory,file)))throw new Error(`${id} is missing ${file}`);cpSync(directory,join(outputRoot,'builtin',id),{recursive:true,force:true});const files=required.map(name=>[name,readFileSync(join(directory,name))]);writeFileSync(join(outputRoot,'archives',`${id}.zip`),zip(files))}
console.log(`Generated ${apps.length} application packages.`);
