import {Router,type RequestHandler} from 'express';
import type {Settings,ShellSession} from '../../shared/types/domain.js';
import {requireObject} from '../middleware/http.js';
import {DataService} from '../services/dataService.js'; import {FileService} from '../services/fileService.js'; import {TerminalService} from '../services/terminalService.js'; import {SystemMonitorService} from '../services/systemMonitorService.js'; import {AppRegistryService} from '../services/appRegistryService.js';
const fail=(message:string,code='VALIDATION_ERROR',status=400)=>Object.assign(new Error(message),{status,code});
const owner=(request:{get(name:string):string|undefined})=>{const id=request.get('x-fluida-session');if(!id||!/^[-\w]{1,128}$/.test(id))throw fail('A valid x-fluida-session header is required','UNAUTHORIZED',401);return id;};
const route=(handler:RequestHandler):RequestHandler=>(request,response,next)=>Promise.resolve(handler(request,response,next)).catch(next);
export function apiRouter(files=new FileService(),data=new DataService(),services:{terminal?:TerminalService;monitor?:SystemMonitorService;registry?:AppRegistryService}={}){const terminal=services.terminal??new TerminalService(files),monitor=services.monitor??new SystemMonitorService(files,terminal),registry=services.registry??new AppRegistryService(undefined,undefined,data.apps.map(app=>({manifest:{...app,version:'1.0.0',entryPoint:`builtin:${app.id}`,capabilities:[]},source:{kind:'builtin'},enabled:true,installedAt:new Date(0).toISOString()})));const router=Router();
router.get('/fs',route(async(req,res)=>{if(req.query.path!==undefined&&typeof req.query.path!=='string')throw fail('path must be a string');res.json({success:true,data:await files.list(typeof req.query.path==='string'?req.query.path:'')});}));router.post('/fs/read',requireObject(['path']),route(async(req,res)=>res.json({success:true,data:{content:await files.read(req.body.path)}})));router.post('/fs/write',requireObject(['path','content']),route(async(req,res)=>{await files.write(req.body.path,req.body.content);res.json({success:true,data:null});}));router.post('/fs/mkdir',requireObject(['path']),route(async(req,res)=>{await files.mkdir(req.body.path);res.status(201).json({success:true,data:null});}));router.post('/fs/rename',requireObject(['from','to']),route(async(req,res)=>{await files.rename(req.body.from,req.body.to);res.json({success:true,data:null});}));router.post('/fs/import',requireObject(['directory','name','content']),route(async(req,res)=>res.status(201).json({success:true,data:await files.importBase64(req.body.directory,req.body.name,req.body.content)})));router.get('/fs/download',route(async(req,res)=>{if(typeof req.query.path!=='string')throw fail('path must be a string');res.download(files.resolve(req.query.path),files.normalizeFilename(req.query.path.split('/').at(-1)||'download'));}));router.delete('/fs',requireObject(['path']),route(async(req,res)=>{await files.delete(req.body.path);res.json({success:true,data:null});}));
router.post('/fs/copy',requireObject(['from','to']),route(async(req,res)=>{await files.copy(req.body.from,req.body.to);res.status(201).json({success:true,data:await files.stat(req.body.to)});}));
router.get('/apps',route(async(_req,res)=>res.json({success:true,data:await registry.list()})));router.post('/apps/install',requireObject(['packagePath']),route(async(req,res)=>res.status(201).json({success:true,data:await registry.install(req.body.packagePath)})));router.patch('/apps/:id',route(async(req,res)=>{if(typeof req.body?.enabled!=='boolean')throw fail('enabled must be a boolean');res.json({success:true,data:await registry.setEnabled(req.params.id,req.body.enabled)});}));router.delete('/apps/:id',route(async(req,res)=>{await registry.uninstall(req.params.id);res.json({success:true,data:null});}));
router.get('/shell/session',route(async(_req,res)=>res.json({success:true,data:await data.session.read()})));router.put('/shell/session',route(async(req,res)=>{if(!req.body||typeof req.body!=='object'||!Array.isArray(req.body.workspaces))throw fail('Invalid shell session');res.json({success:true,data:await data.saveSession(req.body as ShellSession)});}));
router.get('/settings',route(async(_req,res)=>res.json({success:true,data:await data.settings.read()})));router.put('/settings',route(async(req,res)=>{const allowed=['theme','accent','wallpaper','fontScale','dockPosition','animation','reducedMotion','volume','brightness','notifications','accessibility','desktop','defaultApplications','filesView'];if(!req.body||typeof req.body!=='object'||Array.isArray(req.body)||Object.keys(req.body).some(key=>!allowed.includes(key)))throw fail('Invalid settings payload');const value={...await data.settings.read(),...req.body} as Settings;if(!['light','dark','system'].includes(value.theme)||!['bottom','left','right'].includes(value.dockPosition)||!['grid','list'].includes(value.filesView)||!/^#[0-9a-f]{6}$/i.test(value.accent)||value.fontScale<.8||value.fontScale>1.4||value.volume<0||value.volume>100||value.brightness<10||value.brightness>100)throw fail('Invalid setting value');res.json({success:true,data:await data.saveSettings(req.body)});}));router.delete('/settings',route(async(_req,res)=>res.json({success:true,data:await data.resetSettings()})));
router.post('/terminal/jobs',requireObject(['command','cwd']),route(async(req,res)=>res.status(201).json({success:true,data:await terminal.execute(owner(req),req.body)})));router.get('/terminal/jobs',route(async(req,res)=>res.json({success:true,data:terminal.list(owner(req))})));router.delete('/terminal/jobs/:id',route(async(req,res)=>res.json({success:true,data:terminal.terminate(owner(req),req.params.id)})));router.get('/system/resources',route(async(_req,res)=>res.json({success:true,data:await monitor.snapshot()})));router.delete('/system/jobs/:id',route(async(req,res)=>res.json({success:true,data:terminal.terminate(owner(req),req.params.id)})));
router.get('/notes',route(async(req,res)=>{const q=typeof req.query.q==='string'?req.query.q.toLowerCase():'';res.json({success:true,data:(await data.notes.read()).filter(note=>`${note.title} ${note.body}`.toLowerCase().includes(q))});}));router.post('/notes',requireObject(['title','body']),route(async(req,res)=>res.status(201).json({success:true,data:await data.saveNote(req.body)})));router.delete('/notes/:id',route(async(req,res)=>{await data.notes.write((await data.notes.read()).filter(note=>note.id!==req.params.id));res.json({success:true,data:null});}));router.get('/notifications',route(async(_req,res)=>res.json({success:true,data:await data.notifications.read()})));router.patch('/notifications/:id',route(async(req,res)=>{if(typeof req.body?.read!=='boolean')throw fail('read must be a boolean');const rows=await data.notifications.read(),row=rows.find(notification=>notification.id===req.params.id);if(!row)throw fail('Notification not found','NOT_FOUND',404);row.read=req.body.read;await data.notifications.write(rows);res.json({success:true,data:row});}));router.delete('/notifications/:id',route(async(req,res)=>{await data.notifications.write((await data.notifications.read()).filter(notification=>notification.id!==req.params.id));res.json({success:true,data:null});}));router.get('/system',route(async(_req,res)=>res.json({success:true,data:await monitor.snapshot()})));return router;}
