import {Router,type RequestHandler} from 'express';
import type {Settings} from '../../shared/types/domain.js';
import {requireObject} from '../middleware/http.js';
import {DataService} from '../services/dataService.js'; import {FileService} from '../services/fileService.js'; import {TerminalService} from '../services/terminalService.js'; import {SystemMonitorService} from '../services/systemMonitorService.js'; import {AppRegistryService} from '../services/appRegistryService.js';
const fail=(message:string,code='VALIDATION_ERROR',status=400)=>Object.assign(new Error(message),{status,code});
const owner=(response:{locals:Record<string,unknown>})=>{const id=response.locals.ownerId;if(typeof id!=='string'||!/^[-\w]{1,128}$/.test(id))throw fail('Authenticated session is required','UNAUTHORIZED',401);return id;};
const isRecord=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
function validateSettingsPatch(value:unknown):asserts value is Partial<Settings>{if(!isRecord(value))throw fail('Invalid settings payload');const validators:Record<string,(entry:unknown)=>boolean>={theme:entry=>typeof entry==='string'&&['light','dark','system'].includes(entry),accent:entry=>typeof entry==='string'&&/^#[0-9a-f]{6}$/i.test(entry),wallpaper:entry=>typeof entry==='string'&&['aurora','ember','lagoon','dusk'].includes(entry),fontScale:entry=>typeof entry==='number'&&Number.isFinite(entry)&&entry>=.8&&entry<=1.4,dockPosition:entry=>typeof entry==='string'&&['bottom','left','right'].includes(entry),animation:entry=>typeof entry==='string'&&['full','reduced','none'].includes(entry),reducedMotion:entry=>typeof entry==='boolean',volume:entry=>typeof entry==='number'&&Number.isFinite(entry)&&entry>=0&&entry<=100,brightness:entry=>typeof entry==='number'&&Number.isFinite(entry)&&entry>=10&&entry<=100,notifications:entry=>isRecord(entry)&&Object.keys(entry).every(key=>['enabled','sound','showPreviews','doNotDisturb'].includes(key))&&Object.values(entry).every(item=>typeof item==='boolean')};for(const [key,entry] of Object.entries(value))if(!validators[key]?.(entry))throw fail('Invalid setting value');}
const route=(handler:RequestHandler):RequestHandler=>(request,response,next)=>Promise.resolve(handler(request,response,next)).catch(next);
export function apiRouter(files=new FileService(),data=new DataService(),services:{terminal?:TerminalService;monitor?:SystemMonitorService;registry?:AppRegistryService}={}){const terminal=services.terminal??new TerminalService(files),monitor=services.monitor??new SystemMonitorService(files,terminal),registry=services.registry??new AppRegistryService(undefined,undefined,data.apps.map(app=>({manifest:{...app,version:'1.0.0',entryPoint:`builtin:${app.id}`,capabilities:[]},source:{kind:'builtin'},enabled:true,installedAt:new Date(0).toISOString()})));const router=Router();
router.get('/fs',route(async(req,res)=>{if(req.query.path!==undefined&&typeof req.query.path!=='string')throw fail('path must be a string');res.json({success:true,data:await files.list(typeof req.query.path==='string'?req.query.path:'')});}));router.post('/fs/read',requireObject(['path']),route(async(req,res)=>res.json({success:true,data:{content:await files.read(req.body.path)}})));router.post('/fs/write',requireObject(['path','content']),route(async(req,res)=>{await files.write(req.body.path,req.body.content);res.json({success:true,data:null});}));router.post('/fs/mkdir',requireObject(['path']),route(async(req,res)=>{await files.mkdir(req.body.path);res.status(201).json({success:true,data:null});}));router.post('/fs/rename',requireObject(['from','to']),route(async(req,res)=>{await files.rename(req.body.from,req.body.to);res.json({success:true,data:null});}));router.post('/fs/import',requireObject(['directory','name','content']),route(async(req,res)=>res.status(201).json({success:true,data:await files.importBase64(req.body.directory,req.body.name,req.body.content)})));router.get('/fs/download',route(async(req,res)=>{if(typeof req.query.path!=='string')throw fail('path must be a string');res.download(files.resolve(req.query.path),files.normalizeFilename(req.query.path.split('/').at(-1)||'download'));}));router.delete('/fs',requireObject(['path']),route(async(req,res)=>{await files.delete(req.body.path);res.json({success:true,data:null});}));
router.get('/apps',route(async(_req,res)=>res.json({success:true,data:(await registry.list()).filter(app=>app.enabled)})));router.post('/apps/install',requireObject(['packagePath']),route(async(req,res)=>res.status(201).json({success:true,data:await registry.install(req.body.packagePath)})));router.patch('/apps/:id',route(async(req,res)=>{if(typeof req.body?.enabled!=='boolean')throw fail('enabled must be a boolean');res.json({success:true,data:await registry.setEnabled(req.params.id,req.body.enabled)});}));router.delete('/apps/:id',route(async(req,res)=>{await registry.uninstall(req.params.id);res.json({success:true,data:null});}));
router.get('/shell/session',route(async(_req,res)=>res.json({success:true,data:await data.session.read()})));router.put('/shell/session',route(async(req,res)=>res.json({success:true,data:await data.saveSession(req.body)})));
router.get('/settings',route(async(_req,res)=>res.json({success:true,data:await data.settings.read()})));router.put('/settings',route(async(req,res)=>{validateSettingsPatch(req.body);res.json({success:true,data:await data.saveSettings(req.body)});}));
router.post('/terminal/jobs',requireObject(['command','cwd']),route(async(req,res)=>res.status(201).json({success:true,data:await terminal.execute(owner(res),req.body)})));router.get('/terminal/jobs',route(async(_req,res)=>res.json({success:true,data:terminal.list(owner(res))})));router.delete('/terminal/jobs/:id',route(async(req,res)=>res.json({success:true,data:terminal.terminate(owner(res),req.params.id)})));router.get('/system/resources',route(async(_req,res)=>res.json({success:true,data:await monitor.snapshot(owner(res))})));router.delete('/system/jobs/:id',route(async(req,res)=>res.json({success:true,data:terminal.terminate(owner(res),req.params.id)})));
router.get('/notes',route(async(req,res)=>{const q=typeof req.query.q==='string'?req.query.q.toLowerCase():'';res.json({success:true,data:(await data.notes.read()).filter(note=>`${note.title} ${note.body}`.toLowerCase().includes(q))});}));router.post('/notes',requireObject(['title','body']),route(async(req,res)=>res.status(201).json({success:true,data:await data.saveNote(req.body)})));router.delete('/notes/:id',route(async(req,res)=>{await data.notes.update(notes=>notes.filter(note=>note.id!==req.params.id));res.json({success:true,data:null});}));router.get('/notifications',route(async(_req,res)=>res.json({success:true,data:await data.notifications.read()})));router.patch('/notifications/:id',route(async(req,res)=>{if(typeof req.body?.read!=='boolean')throw fail('read must be a boolean');let row;await data.notifications.update(rows=>{row=rows.find(notification=>notification.id===req.params.id);if(!row)throw fail('Notification not found','NOT_FOUND',404);row.read=req.body.read;return rows;});res.json({success:true,data:row});}));router.delete('/notifications/:id',route(async(req,res)=>{await data.notifications.update(rows=>rows.filter(notification=>notification.id!==req.params.id));res.json({success:true,data:null});}));router.get('/system',route(async(_req,res)=>res.json({success:true,data:await monitor.snapshot(owner(res))})));return router;}
