import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {FileService} from '../services/fileService.js';import {DataService} from '../services/dataService.js';import {errorHandler,requireObject} from '../middleware/http.js';
import {JsonRepository} from '../services/jsonRepository.js';
async function temporary(){return fs.mkdtemp(path.join(os.tmpdir(),'fluida-'));}
test('storage paths remain contained',async()=>{const root=await temporary(),files=new FileService(root);assert.equal(files.resolve('docs/a.txt'),path.join(root,'docs/a.txt'));assert.throws(()=>files.resolve('../secret'),/escapes/);assert.throws(()=>files.resolve('/etc/passwd'),/Invalid/);});
test('file operations create, read, list, rename and delete',async()=>{const files=new FileService(await temporary());await files.write('docs/a.txt','hello');assert.equal(await files.read('docs/a.txt'),'hello');assert.equal((await files.list('docs'))[0].name,'a.txt');await files.rename('docs/a.txt','docs/b.txt');assert.equal(await files.read('docs/b.txt'),'hello');await files.delete('docs');assert.deepEqual(await files.list(),[]);});
test('settings and notes persist between service instances',async()=>{const root=await temporary(),first=new DataService(root);await first.saveSettings({accent:'#123456'});const note=await first.saveNote({title:'Persistent',body:'Yes'}),second=new DataService(root);assert.equal((await second.settings.read()).accent,'#123456');assert.equal((await second.notes.read())[0].id,note.id);});
test('API request middleware validates required string bodies',()=>{const middleware=requireObject(['path','content']),responses:any[]=[];const response={status(code:number){responses.push(code);return this;},json(value:unknown){responses.push(value);return this;}} as any;let advanced=false;middleware({body:{path:'only-path'}} as any,response,()=>{advanced=true;});assert.equal(responses[0],400);assert.equal(responses[1].error.code,'VALIDATION_ERROR');middleware({body:{path:'a.txt',content:'safe'}} as any,response,()=>{advanced=true;});assert.equal(advanced,true);});
test('error handler logs internal errors and returns fixed public messages',()=>{const responses:any[]=[],original=console.error,logged:any[]=[];console.error=(...values)=>{logged.push(values);};try{const response={status(code:number){responses.push(code);return this;},json(value:unknown){responses.push(value);return this;}} as any;errorHandler(Object.assign(new Error('/private/path missing'),{code:'ENOENT'}),{} as any,response,()=>{});assert.equal(responses[0],404);assert.equal(responses[1].error.message,'Resource not found');assert.equal(logged.length,1);}finally{console.error=original;}});
test('repository updates serialize concurrent read-modify-write operations',async()=>{const root=await temporary(),repository=new JsonRepository(path.join(root,'rows.json'),[] as string[]);await Promise.all([repository.update(async rows=>{await new Promise(resolve=>setTimeout(resolve,10));rows.push('first');return rows;}),repository.update(rows=>{rows.push('second');return rows;})]);assert.deepEqual(await repository.read(),['first','second']);});
test('concurrent settings and note updates retain independent changes',async()=>{const data=new DataService(await temporary());await Promise.all([data.saveSettings({accent:'#123456'}),data.saveSettings({theme:'light'})]);const settings=await data.settings.read();assert.equal(settings.accent,'#123456');assert.equal(settings.theme,'light');await Promise.all([data.saveNote({title:'One',body:'1'}),data.saveNote({title:'Two',body:'2'})]);assert.equal((await data.notes.read()).length,2);});
test('file operations reject symlinks that resolve outside storage',async()=>{const root=await temporary(),outside=await temporary(),files=new FileService(root);await fs.writeFile(path.join(outside,'secret.txt'),'secret');await fs.symlink(path.join(outside,'secret.txt'),path.join(root,'secret-link'));await fs.symlink(outside,path.join(root,'outside-dir'));assert.throws(()=>files.resolve('secret-link'),/escapes/);assert.throws(()=>files.resolve('outside-dir/new.txt'),/escapes/);});
